# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Aaron
paginate:       5
baseurl:        ""
url:            "https://aaronheee.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Aaron He
  url:          
  email:        aaronheee@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
gems:
  - jekyll-paginate
